myblog/human/urls.py
from django.urls import path

from .views import *
urlpatterns = [
    path('', index, name='main'),
    path('about/',about,name='about')
]

myblog/myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from human.views import *
from myblog import settings

handler404 = ''

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('human.urls')),
    path('article/', include('article.urls')),
    path('', include('authorization.urls')),
    path('', include('drfsite.urls')),
    path('', include('uptrade.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, documents_root=settings.MEDIA_ROOT)

myblog/uptrade/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('menu/', index, name='menu'),
    path('menu/<slug:menu_slug>', cat, name='advmenu')
]

myblog/uptrade/models.py
from django.db import models

class MainMenu(models.Model):
    name = models.CharField(max_length=50)
    url_slug = models.SlugField(unique=True, db_index=True, verbose_name="Url")
    class Meta:
        verbose_name = 'Главное меню'
        verbose_name_plural = 'Главное меню'

    def __str__(self):
        return self.name

class SubMenu(models.Model):
    main_cat = models.ForeignKey(MainMenu, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    url_slug = models.SlugField(unique=True, db_index=True, verbose_name="Url")

    class Meta:
        verbose_name = 'Подменю'
        verbose_name_plural = 'Подменю'

    def __str__(self):
        return self.main_cat.name + ' -- ' + self.name

myblog/uptrade/views.py
from django.shortcuts import render

def index(request):
    return render(request,'uptrade/base.html', {'page': 'main'})

def cat(request, menu_slug):
    page = menu_slug
    return render(request,'uptrade/base.html', {'page': page})

myblog/uptrade/templates/uptrade/base.html
{% load uptrade_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Тайтл</title>
</head>
<body>
    {% draw_menu 'main_menu'%}
    <h1> Страница со слагом {{page}}</h1>
</body>
</html>

myblog/uptrade/templates/uptrade/custom.html
<h1>Меню с названием {{name}}</h1>
{% for c in menu %}
    {%for cat in c.submenu_set.all %}
<ul>
    <li>
        <a href="{% url 'advmenu' c.url_slug %}">{{c.name}}</a>
        <a href="{% url 'advmenu' cat.url_slug %}">{{cat.name}}</a>
    </li>
</ul>
{%endfor%}
{% endfor %}